name: Cross Platform Tests
on: 
  [pull_request, push]
jobs:
  run-ios-tests:
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - name: Checkout internal
        uses: actions/checkout@v2
        with:
          path: ios-sdk
      - name: Checkout cross-platform-tests
        uses: actions/checkout@v2
        with:
          ref: initial #remove or change to development/master when initial PR is merged
          token: ${{ secrets.APPLE_SDK_PAT }}  #medium-term solution, this needs to be an MParticle/non-personal PAT
          repository: mParticle/crossplatform-sdk-tests
          path: crossplatform-sdk-tests
      - name: Checkout submodules
        working-directory: crossplatform-sdk-tests
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.APPLE_SDK_PAT }}:${{ secrets.APPLE_SDK_PAT }}@github.com\//")
          done
          git submodule sync
          git submodule update --init
      - name: Replace crossplatform-sdk-tests' Apple submodule with current commit
        run: rm -rf crossplatform-sdk-tests/.sdks/apple/*; mv -v ios-sdk/* crossplatform-sdk-tests/.sdks/apple
      - name: Install Cocoapods
        working-directory: crossplatform-sdk-tests
        run: sudo gem install cocoapods; sudo gem install cocoapods-generate
      - name: Import Project
        working-directory: crossplatform-sdk-tests
        run: ./gradlew :testing:podImport
      - name: Run Tests
        working-directory: crossplatform-sdk-tests
        run: ./gradlew runIos
