name: iOS SDK Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Do a dry run to preview instead of a real release [true/false]"
        required: true
        default: "true"

jobs:
    # SDK release is done from public/master branch.
  confirm-master-branch:
    name: "Confirm release is run on master branch"
    runs-on: macOS-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: |
          BRANCHNAME=${GITHUB_REF##*/}
          echo "pulling branch name, branch name is:"
          echo $BRANCHNAME
          if [ $BRANCHNAME != "master" ]
          then
            echo "You can only run a release from the master branch, you are trying to run it from ${BRANCHNAME}"
            exit 1
          fi
  create-release-branch:
    runs-on: macOS-latest
    needs: confirm-master-branch
    steps:
      - name: "Checkout Internal Development Branch"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: BrandonStalnaker/mparticle-apple-sdk
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: development
      - name: "Merge back release commits to public/master repository"
        run: git checkout -b release/${{ github.run_number }}; git push origin release/${{ github.run_number }}
  release:
    runs-on: macOS-latest
    needs: create-release-branch
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate environment and no-location patch
        run: |
          env | grep -q '^GITHUB_ACCESS_TOKEN=' || (echo "Required environment variable GITHUB_ACCESS_TOKEN is not set" && exit 1)
          env | grep -q '^COCOAPODS_TRUNK_TOKEN=' || (echo "Required environment variable COCOAPODS_TRUNK_TOKEN is not set" && exit 1)
          git apply Scripts/0001-DISABLE-LOCATION.patch || (echo "Disable location patch could not be successfully applied" && exit 1)
          git checkout .

      - name: Setup git config
        run: |
          git config user.email "developers@mparticle.com"
          git config user.name "mParticle Automation"
          
      - name: "Checkout public/master Branch"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: master
      - name: "Add new release branch commits to public/master for release"
        run: |
          git remote add internal https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/BrandonStalnaker/mparticle-apple-sdk.git
          git fetch internal
          git pull internal release/${{ github.run_number }}

      - name: Release --dry-run
        if: ${{ github.event.inputs.dryRun == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release --dry-run

      - name: Release
        if: ${{ github.event.inputs.dryRun == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @semantic-release/exec@5 \
          semantic-release
          
      - name: "Merge back release commits to release branch"
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git push internal HEAD:release/${{ github.run_number }}

      - name: Release to CocoaPods
        if: ${{ github.event.inputs.dryRun == 'false'}}
        run: |
          sudo gem install xcodeproj
          #pod trunk push --allow-warnings

  sync-repository:
    needs: release
    runs-on: macOS-latest
    steps:
      - name: "Checkout public/master Branch"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: master
      - name: "Add new release branch commits to public/master for release"
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git remote add internal https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/BrandonStalnaker/mparticle-apple-sdk.git
          git fetch internal
          git pull internal release/${{ github.run_number }}
      - name: "Merge back release commits to public/master repository"
        if: ${{ github.event.inputs.dryRun == 'false'}}
        run: |
          git push origin HEAD:master
      - name: "Merge back release commits to internal repository"
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git push internal HEAD:development
          git push internal HEAD:master
      - name: "Delete Release Branch"
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git push --delete internal release/${{ github.run_number }}
